import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import { PaymentScheduleItem, EMICalculation, EMIInput } from '../types';
import { formatCurrency, formatNumber } from './calculations';
import { format } from 'date-fns';

export const exportToPDF = (
  calculation: EMICalculation,
  inputs: EMIInput,
  schedule: PaymentScheduleItem[],
  calculatorType: string = 'EMI'
) => {
  const doc = new jsPDF();
  let currentPage = 1;
  
  // Helper function to add header to each page
  const addHeader = (pageNum: number) => {
    // Header background
    doc.setFillColor(41, 98, 255);
    doc.rect(0, 0, 210, 25, 'F');
    
    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(`${calculatorType} Calculator Report`, 20, 15);
    
    // Page number
    doc.setFontSize(10);
    doc.text(`Page ${pageNum}`, 170, 15);
    
    // Reset text color
    doc.setTextColor(0, 0, 0);
  };
  
  // Helper function to add footer to each page
  const addFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by EMI Calculator App - For informational purposes only', 20, 290);
    doc.text(`Generated on: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, 20, 285);
  };
  
  // Page 1 - Summary
  addHeader(currentPage);
  
  let yPos = 40;
  
  // Loan Details Section
  doc.setFillColor(248, 250, 252);
  doc.rect(15, yPos - 5, 180, 70, 'F');
  doc.setDrawColor(229, 231, 235);
  doc.rect(15, yPos - 5, 180, 70);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(31, 41, 55);
  doc.text('Loan Details', 20, yPos + 5);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  yPos += 15;
  
  if (calculatorType === 'EMI') {
    const loanDetails = [
      ['Loan Type:', `${inputs.loanType.charAt(0).toUpperCase() + inputs.loanType.slice(1)} Loan`],
      ['Principal Amount:', `Rs. ${Math.round(inputs.principal).toLocaleString('en-IN')}`],
      ['Interest Rate:', `${inputs.interestRate}% per annum`],
      ['Loan Term:', `${inputs.term} ${inputs.termUnit}`],
      ['Start Date:', format(inputs.startDate, 'dd/MM/yyyy')],
      ['Payment Frequency:', inputs.paymentFrequency]
    ];
    
    loanDetails.forEach(([label, value]) => {
      doc.setFont('helvetica', 'bold');
      doc.text(label, 25, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(value, 80, yPos);
      yPos += 8;
    });
  }
  
  yPos += 15;
  
  // Results Summary Section
  doc.setFillColor(254, 249, 195);
  doc.rect(15, yPos - 5, 180, 55, 'F');
  doc.setDrawColor(245, 158, 11);
  doc.rect(15, yPos - 5, 180, 55);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(146, 64, 14);
  doc.text('Calculation Results', 20, yPos + 5);
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  yPos += 15;
  
  const results = [
    ['Monthly EMI:', `Rs. ${Math.round(calculation.emi).toLocaleString('en-IN')}`],
    ['Total Payment:', `Rs. ${Math.round(calculation.totalPayment).toLocaleString('en-IN')}`],
    ['Total Interest:', `Rs. ${Math.round(calculation.totalInterest).toLocaleString('en-IN')}`],
    ['Interest as % of Total:', `${((calculation.totalInterest / calculation.totalPayment) * 100).toFixed(2)}%`]
  ];
  
  results.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 25, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 80, yPos);
    yPos += 8;
  });
  
  addFooter();
  
  // Payment Schedule Pages
  if (schedule.length > 0) {
    doc.addPage();
    currentPage++;
    addHeader(currentPage);
    
    yPos = 40;
    
    // Schedule header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(31, 41, 55);
    doc.text(`Complete Payment Schedule (${schedule.length} payments)`, 20, yPos);
    yPos += 15;
    
    // Table header
    doc.setFillColor(59, 130, 246);
    doc.rect(15, yPos - 3, 170, 12, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    
    const headers = ['Month', 'Date', 'EMI (Rs.)', 'Principal (Rs.)', 'Interest (Rs.)', 'Balance (Rs.)'];
    const columnWidths = [25, 30, 30, 35, 35, 35];
    let xPos = 20;
    
    headers.forEach((header, index) => {
      doc.text(header, xPos, yPos + 6);
      xPos += columnWidths[index];
    });
    
    yPos += 12;
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    
    // Payment rows
    schedule.forEach((payment, index) => {
      if (yPos > 270) {
        addFooter();
        doc.addPage();
        currentPage++;
        addHeader(currentPage);
        yPos = 40;
        
        // Repeat table header on new page
        doc.setFillColor(59, 130, 246);
        doc.rect(15, yPos - 3, 170, 12, 'F');
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        
        xPos = 20;
        headers.forEach((header, index) => {
          doc.text(header, xPos, yPos + 6);
          xPos += columnWidths[index];
        });
        
        yPos += 12;
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'normal');
      }
      
      // Alternate row background
      if (index % 2 === 0) {
        doc.setFillColor(249, 250, 251);
        doc.rect(15, yPos - 2, 170, 8, 'F');
      }
      
      doc.setFontSize(8);
      xPos = 20;
      
      const rowData = [
        payment.month.toString(),
        format(payment.date, 'MMM yy'),
        Math.round(payment.emi).toLocaleString('en-IN'),
        Math.round(payment.principal).toLocaleString('en-IN'),
        Math.round(payment.interest).toLocaleString('en-IN'),
        Math.round(payment.balance).toLocaleString('en-IN')
      ];
      
      rowData.forEach((data, colIndex) => {
        // Right align currency values
        if (colIndex > 1) {
          const textWidth = doc.getTextWidth(data);
          doc.text(data, xPos + columnWidths[colIndex] - textWidth - 2, yPos + 4);
        } else {
          doc.text(data, xPos, yPos + 4);
        }
        xPos += columnWidths[colIndex];
      });
      
      yPos += 8;
    });
    
    addFooter();
  }
  
  doc.save(`${calculatorType.toLowerCase()}-calculation-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
};

export const exportToExcel = (
  calculation: EMICalculation,
  inputs: EMIInput,
  schedule: PaymentScheduleItem[],
  calculatorType: string = 'EMI'
) => {
  const workbook = XLSX.utils.book_new();
  
  // Enhanced Summary Sheet
  const summaryData = [
    ['EMI CALCULATOR REPORT', '', '', ''],
    ['Generated on:', format(new Date(), 'dd/MM/yyyy HH:mm:ss'), '', ''],
    ['', '', '', ''],
    ['LOAN DETAILS', '', '', ''],
    ...(calculatorType === 'EMI' ? [
      ['Loan Type:', inputs.loanType.charAt(0).toUpperCase() + inputs.loanType.slice(1) + ' Loan', '', ''],
      ['Principal Amount:', `₹${inputs.principal.toLocaleString('en-IN')}`, '', ''],
      ['Interest Rate (% p.a.):', `${inputs.interestRate}%`, '', ''],
      ['Loan Term:', `${inputs.term} ${inputs.termUnit}`, '', ''],
      ['Start Date:', format(inputs.startDate, 'dd/MM/yyyy'), '', ''],
      ['Payment Frequency:', inputs.paymentFrequency, '', ''],
    ] : []),
    ['', '', '', ''],
    ['CALCULATION RESULTS', '', '', ''],
    ['Monthly EMI:', `₹${calculation.emi.toLocaleString('en-IN')}`, '', ''],
    ['Total Payment:', `₹${calculation.totalPayment.toLocaleString('en-IN')}`, '', ''],
    ['Total Interest:', `₹${calculation.totalInterest.toLocaleString('en-IN')}`, '', ''],
    ['Principal Amount:', `₹${calculation.principal.toLocaleString('en-IN')}`, '', ''],
    ['Interest as % of Total:', `${((calculation.totalInterest / calculation.totalPayment) * 100).toFixed(2)}%`, '', ''],
    ['Total Payments:', `${schedule.length} payments`, '', ''],
    ['', '', '', ''],
    ['BREAKDOWN ANALYSIS', '', '', ''],
    ['Amount paid towards Principal:', `₹${calculation.principal.toLocaleString('en-IN')}`, `${((calculation.principal / calculation.totalPayment) * 100).toFixed(2)}%`, ''],
    ['Amount paid towards Interest:', `₹${calculation.totalInterest.toLocaleString('en-IN')}`, `${((calculation.totalInterest / calculation.totalPayment) * 100).toFixed(2)}%`, ''],
    ['You pay extra:', `₹${calculation.totalInterest.toLocaleString('en-IN')}`, 'as interest over loan amount', '']
  ];
  
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  
  // Enhanced formatting for summary
  const summaryRange = XLSX.utils.decode_range(summarySheet['!ref'] || 'A1');
  
  // Title formatting
  if (summarySheet['A1']) {
    summarySheet['A1'].s = {
      font: { bold: true, size: 16, color: { rgb: '2563EB' } },
      fill: { fgColor: { rgb: 'DBEAFE' } },
      alignment: { horizontal: 'center' }
    };
  }
  
  // Section headers formatting
  ['A4', 'A13', 'A21'].forEach(cell => {
    if (summarySheet[cell]) {
      summarySheet[cell].s = {
        font: { bold: true, size: 12, color: { rgb: '1F2937' } },
        fill: { fgColor: { rgb: 'F3F4F6' } }
      };
    }
  });
  
  // Set column widths
  summarySheet['!cols'] = [
    { width: 25 },
    { width: 20 },
    { width: 15 },
    { width: 10 }
  ];
  
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');
  
  // Enhanced Payment Schedule Sheet
  if (schedule.length > 0) {
    const scheduleData = [
      ['Month #', 'Payment Date', 'EMI Amount (₹)', 'Principal (₹)', 'Interest (₹)', 'Outstanding Balance (₹)', 'Cumulative Principal (₹)', 'Cumulative Interest (₹)'],
      ...schedule.map((payment, index) => {
        const cumulativePrincipal = schedule.slice(0, index + 1).reduce((sum, p) => sum + p.principal, 0);
        const cumulativeInterest = schedule.slice(0, index + 1).reduce((sum, p) => sum + p.interest, 0);
        
        return [
          payment.month,
          format(payment.date, 'dd/MM/yyyy'),
          Math.round(payment.emi),
          Math.round(payment.principal),
          Math.round(payment.interest),
          Math.round(payment.balance),
          Math.round(cumulativePrincipal),
          Math.round(cumulativeInterest)
        ];
      })
    ];
    
    const scheduleSheet = XLSX.utils.aoa_to_sheet(scheduleData);
    
    // Enhanced formatting for schedule
    const scheduleRange = XLSX.utils.decode_range(scheduleSheet['!ref'] || 'A1');
    
    // Header row formatting
    for (let C = scheduleRange.s.c; C <= scheduleRange.e.c; ++C) {
      const address = XLSX.utils.encode_col(C) + '1';
      if (!scheduleSheet[address]) continue;
      scheduleSheet[address].s = {
        font: { bold: true, color: { rgb: 'FFFFFF' } },
        fill: { fgColor: { rgb: '3B82F6' } },
        alignment: { horizontal: 'center' }
      };
    }
    
    // Set column widths
    scheduleSheet['!cols'] = [
      { width: 10 }, // Month
      { width: 12 }, // Date
      { width: 15 }, // EMI
      { width: 15 }, // Principal
      { width: 15 }, // Interest
      { width: 18 }, // Balance
      { width: 18 }, // Cum Principal
      { width: 18 }  // Cum Interest
    ];
    
    XLSX.utils.book_append_sheet(workbook, scheduleSheet, 'Complete Payment Schedule');
  }
  
  // Enhanced Yearly Summary Sheet
  if (schedule.length > 0) {
    const yearlyData = schedule.reduce((acc, payment) => {
      const year = payment.year;
      if (!acc[year]) {
        acc[year] = { year, emi: 0, principal: 0, interest: 0, payments: 0, avgBalance: 0 };
      }
      acc[year].emi += payment.emi;
      acc[year].principal += payment.principal;
      acc[year].interest += payment.interest;
      acc[year].avgBalance += payment.balance;
      acc[year].payments += 1;
      return acc;
    }, {} as Record<number, any>);
    
    // Calculate average balance for each year
    Object.values(yearlyData).forEach((year: any) => {
      year.avgBalance = year.avgBalance / year.payments;
    });
    
    const yearlyArray = [
      ['Year', 'Number of Payments', 'Total EMI Paid (₹)', 'Principal Paid (₹)', 'Interest Paid (₹)', 'Avg Outstanding (₹)', 'Interest %'],
      ...Object.values(yearlyData).map((year: any) => [
        year.year,
        year.payments,
        Math.round(year.emi),
        Math.round(year.principal),
        Math.round(year.interest),
        Math.round(year.avgBalance),
        `${((year.interest / year.emi) * 100).toFixed(1)}%`
      ])
    ];
    
    const yearlySheet = XLSX.utils.aoa_to_sheet(yearlyArray);
    
    // Header formatting
    const yearlyRange = XLSX.utils.decode_range(yearlySheet['!ref'] || 'A1');
    for (let C = yearlyRange.s.c; C <= yearlyRange.e.c; ++C) {
      const address = XLSX.utils.encode_col(C) + '1';
      if (!yearlySheet[address]) continue;
      yearlySheet[address].s = {
        font: { bold: true, color: { rgb: 'FFFFFF' } },
        fill: { fgColor: { rgb: 'DC2626' } },
        alignment: { horizontal: 'center' }
      };
    }
    
    // Set column widths
    yearlySheet['!cols'] = [
      { width: 8 },  // Year
      { width: 15 }, // Payments
      { width: 18 }, // Total EMI
      { width: 18 }, // Principal
      { width: 18 }, // Interest
      { width: 18 }, // Avg Balance
      { width: 12 }  // Interest %
    ];
    
    XLSX.utils.book_append_sheet(workbook, yearlySheet, 'Yearly Analysis');
  }
  
  // Add a detailed analysis sheet
  if (schedule.length > 0) {
    const analysisData = [
      ['LOAN ANALYSIS INSIGHTS', '', ''],
      ['', '', ''],
      ['Payment Breakdown:', '', ''],
      ['First payment interest:', `₹${Math.round(schedule[0].interest).toLocaleString('en-IN')}`, `${((schedule[0].interest / schedule[0].emi) * 100).toFixed(1)}% of EMI`],
      ['First payment principal:', `₹${Math.round(schedule[0].principal).toLocaleString('en-IN')}`, `${((schedule[0].principal / schedule[0].emi) * 100).toFixed(1)}% of EMI`],
      ['', '', ''],
      ['Last payment interest:', `₹${Math.round(schedule[schedule.length - 1].interest).toLocaleString('en-IN')}`, `${((schedule[schedule.length - 1].interest / schedule[schedule.length - 1].emi) * 100).toFixed(1)}% of EMI`],
      ['Last payment principal:', `₹${Math.round(schedule[schedule.length - 1].principal).toLocaleString('en-IN')}`, `${((schedule[schedule.length - 1].principal / schedule[schedule.length - 1].emi) * 100).toFixed(1)}% of EMI`],
      ['', '', ''],
      ['Key Milestones:', '', ''],
      ['50% principal paid by month:', schedule.findIndex(p => (calculation.principal - p.balance) >= calculation.principal * 0.5) + 1, ''],
      ['75% principal paid by month:', schedule.findIndex(p => (calculation.principal - p.balance) >= calculation.principal * 0.75) + 1, ''],
      ['Interest becomes less than principal at month:', schedule.findIndex(p => p.interest < p.principal) + 1, ''],
      ['', '', ''],
      ['Potential Savings with Prepayment:', '', ''],
      ['If you pay ₹5,000 extra monthly:', 'Interest saved', 'Time saved'],
      ['Estimated benefit:', '₹50,000 - 2,00,000', '2-5 years'],
      ['(Use prepayment calculator for exact figures)', '', '']
    ];
    
    const analysisSheet = XLSX.utils.aoa_to_sheet(analysisData);
    
    // Title formatting
    if (analysisSheet['A1']) {
      analysisSheet['A1'].s = {
        font: { bold: true, size: 14, color: { rgb: '059669' } },
        fill: { fgColor: { rgb: 'ECFDF5' } }
      };
    }
    
    // Set column widths
    analysisSheet['!cols'] = [
      { width: 35 },
      { width: 20 },
      { width: 20 }
    ];
    
    XLSX.utils.book_append_sheet(workbook, analysisSheet, 'Loan Insights');
  }
  
  XLSX.writeFile(workbook, `${calculatorType.toLowerCase()}-detailed-calculation-${format(new Date(), 'yyyy-MM-dd')}.xlsx`);
};

export const generateShareableURL = (
  inputs: any,
  calculatorType: string
): string => {
  const baseURL = window.location.origin + window.location.pathname;
  const params = new URLSearchParams();
  
  params.set('calculator', calculatorType);
  
  // Encode inputs as URL parameters
  Object.keys(inputs).forEach(key => {
    const value = inputs[key];
    if (value !== null && value !== undefined) {
      if (typeof value === 'object' && value instanceof Date) {
        params.set(key, value.toISOString());
      } else if (Array.isArray(value)) {
        params.set(key, JSON.stringify(value));
      } else {
        params.set(key, value.toString());
      }
    }
  });
  
  return `${baseURL}?${params.toString()}`;
};

export const parseURLParams = (): { calculatorType: string; inputs: any } | null => {
  const urlParams = new URLSearchParams(window.location.search);
  const calculatorType = urlParams.get('calculator');
  
  if (!calculatorType) return null;
  
  const inputs: any = {};
  
  urlParams.forEach((value, key) => {
    if (key === 'calculator') return;
    
    try {
      // Try to parse as JSON first (for arrays and objects)
      if (value.startsWith('[') || value.startsWith('{')) {
        inputs[key] = JSON.parse(value);
      } else if (value.includes('T') && value.includes('Z')) {
        // Parse as date
        inputs[key] = new Date(value);
      } else if (!isNaN(Number(value))) {
        // Parse as number
        inputs[key] = Number(value);
      } else if (value === 'true' || value === 'false') {
        // Parse as boolean
        inputs[key] = value === 'true';
      } else {
        // Keep as string
        inputs[key] = value;
      }
    } catch (error) {
      // If parsing fails, keep as string
      inputs[key] = value;
    }
  });
  
  return { calculatorType, inputs };
};

export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const success = document.execCommand('copy');
      textArea.remove();
      return success;
    }
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
};