  // Comprehensive Indian stock symbols database (440 entries)
  // Auto-generated from comprehensive database
  private static readonly INDIAN_STOCKS = {
    'abbott india': 'ABBOTINDIA',
    'abbotindia': 'ABBOTINDIA',
    'abbott': 'ABBOTINDIA',
    'aditya birla fashion': 'ABFRL',
    'abfrl': 'ABFRL',
    'pantaloons': 'ABFRL',
    'acc': 'ACC',
    'acc limited': 'ACC',
    'adani green energy': 'ADANIGREEN',
    'adanigreen': 'ADANIGREEN',
    'adani power': 'ADANIPOWER',
    'adanipower': 'ADANIPOWER',
    'adani transmission': 'ADANITRANS',
    'adanitrans': 'ADANITRANS',
    'alkem laboratories': 'ALKEM',
    'alkem': 'ALKEM',
    'amber enterprises': 'AMBER',
    'amber': 'AMBER',
    'ambuja cements': 'AMBUJACEM',
    'ambujacem': 'AMBUJACEM',
    'ambuja': 'AMBUJACEM',
    'apollo hospitals': 'APOLLOHOSP',
    'apollohosp': 'APOLLOHOSP',
    'apollo': 'APOLLOHOSP',
    'arvind': 'ARVIND',
    'arvind limited': 'ARVIND',
    'ashok leyland': 'ASHOKLEY',
    'ashokley': 'ASHOKLEY',
    'aster dm healthcare': 'ASTERDM',
    'asterdm': 'ASTERDM',
    'aster': 'ASTERDM',
    'aurobindo pharma': 'AUROPHARMA',
    'auropharma': 'AUROPHARMA',
    'aurobindo': 'AUROPHARMA',
    'axis bank': 'AXISBANK',
    'axisbank': 'AXISBANK',
    'axis': 'AXISBANK',
    'bajaj auto': 'BAJAJ-AUTO',
    'bajajauto': 'BAJAJ-AUTO',
    'bajaj': 'BAJAJ-AUTO',
    'bajaj electricals': 'BAJAJELEC',
    'bajajelec': 'BAJAJELEC',
    'bajaj finserv': 'BAJAJFINSV',
    'bajajfinsv': 'BAJAJFINSV',
    'bajaj finance': 'BAJFINANCE',
    'bajfinance': 'BAJFINANCE',
    'balaji telefilms': 'BALAJITELE',
    'balajitele': 'BALAJITELE',
    'balaji': 'BALAJITELE',
    'bandhan bank': 'BANDHANBNK',
    'bandhanbnk': 'BANDHANBNK',
    'bank of baroda': 'BANKBARODA',
    'bankbaroda': 'BANKBARODA',
    'bob': 'BANKBARODA',
    'bharti airtel': 'BHARTIARTL',
    'bhartiartl': 'BHARTIARTL',
    'airtel': 'BHARTIARTL',
    'biocon': 'BIOCON',
    'biocon limited': 'BIOCON',
    'blue star': 'BLUESTARCO',
    'bluestarco': 'BLUESTARCO',
    'bharat petroleum': 'BPCL',
    'bpcl': 'BPCL',
    'bharat petro': 'BPCL',
    'britannia industries': 'BRITANNIA',
    'britannia': 'BRITANNIA',
    'byju's': 'BYJUS',
    'byjus': 'BYJUS',
    'think and learn': 'BYJUS',
    'cadila healthcare': 'CADILAHC',
    'cadilahc': 'CADILAHC',
    'zydus': 'CADILAHC',
    'canara bank': 'CANBK',
    'canbk': 'CANBK',
    'cholamandalam finance': 'CHOLAFIN',
    'cholafin': 'CHOLAFIN',
    'chola': 'CHOLAFIN',
    'cipla': 'CIPLA',
    'cipla limited': 'CIPLA',
    'coal india': 'COALINDIA',
    'coalindia': 'COALINDIA',
    'cil': 'COALINDIA',
    'coforge': 'COFORGE',
    'coforge limited': 'COFORGE',
    'colgate palmolive': 'COLPAL',
    'colpal': 'COLPAL',
    'colgate': 'COLPAL',
    'container corporation': 'CONCOR',
    'concor': 'CONCOR',
    'crompton greaves': 'CROMPTON',
    'crompton': 'CROMPTON',
    'dabur india': 'DABUR',
    'dabur': 'DABUR',
    'dalmia bharat': 'DALMIABHA',
    'dalmiabha': 'DALMIABHA',
    'dalmia': 'DALMIABHA',
    'dilip buildcon': 'DBL',
    'dbl': 'DBL',
    'devyani international': 'DEVYANI',
    'devyani': 'DEVYANI',
    'kfc': 'DEVYANI',
    'divis laboratories': 'DIVISLAB',
    'divislab': 'DIVISLAB',
    'divis lab': 'DIVISLAB',
    'dixon technologies': 'DIXON',
    'dixon': 'DIXON',
    'avenue supermarts': 'DMART',
    'dmart': 'DMART',
    'd mart': 'DMART',
    'dr reddys laboratories': 'DRREDDY',
    'drreddy': 'DRREDDY',
    'dr reddy': 'DRREDDY',
    'eicher motors': 'EICHERMOT',
    'eichermot': 'EICHERMOT',
    'eicher': 'EICHERMOT',
    'emami': 'EMAMI',
    'emami limited': 'EMAMI',
    'escorts': 'ESCORTS',
    'escorts limited': 'ESCORTS',
    'federal bank': 'FEDERALBNK',
    'federalbnk': 'FEDERALBNK',
    'fino payments bank': 'FINO',
    'fino': 'FINO',
    'force motors': 'FORCEMOT',
    'forcemot': 'FORCEMOT',
    'fortis healthcare': 'FORTIS',
    'fortis': 'FORTIS',
    'future retail': 'FRETAIL',
    'fretail': 'FRETAIL',
    'big bazaar': 'FRETAIL',
    'gail': 'GAIL',
    'gas authority of india': 'GAIL',
    'gati': 'GATI',
    'gati limited': 'GATI',
    'glenmark pharmaceuticals': 'GLENMARK',
    'glenmark': 'GLENMARK',
    'gmmco': 'GMMCO',
    'gmmco limited': 'GMMCO',
    'godrej consumer products': 'GODREJCP',
    'godrejcp': 'GODREJCP',
    'godrej': 'GODREJCP',
    'grasim industries': 'GRASIM',
    'grasim': 'GRASIM',
    'gtl infrastructure': 'GTLINFRA',
    'gtlinfra': 'GTLINFRA',
    'gtl': 'GTLINFRA',
    'havells india': 'HAVELLS',
    'havells': 'HAVELLS',
    'healthcare global': 'HCG',
    'hcg': 'HCG',
    'hcl technologies': 'HCLTECH',
    'hcltech': 'HCLTECH',
    'hcl tech': 'HCLTECH',
    'hcl': 'HCLTECH',
    'hdfc bank': 'HDFCBANK',
    'hdfcbank': 'HDFCBANK',
    'hdfc': 'HDFCBANK',
    'hdfc life': 'HDFCLIFE',
    'hdfclife': 'HDFCLIFE',
    'heritage foods': 'HERITGFOOD',
    'heritgfood': 'HERITGFOOD',
    'heritage': 'HERITGFOOD',
    'hero motocorp': 'HEROMOTOCO',
    'heromotoco': 'HEROMOTOCO',
    'hero': 'HEROMOTOCO',
    'hindalco industries': 'HINDALCO',
    'hindalco': 'HINDALCO',
    'hindustan petroleum': 'HINDPETRO',
    'hindpetro': 'HINDPETRO',
    'hpcl': 'HINDPETRO',
    'hindustan unilever': 'HINDUNILVR',
    'hindunilvr': 'HINDUNILVR',
    'hul': 'HINDUNILVR',
    'hindustan zinc': 'HINDZINC',
    'hindzinc': 'HINDZINC',
    'icici bank': 'ICICIBANK',
    'icicibank': 'ICICIBANK',
    'icici': 'ICICIBANK',
    'icici prudential': 'ICICIPRULI',
    'icicipruli': 'ICICIPRULI',
    'icici pru': 'ICICIPRULI',
    'vodafone idea': 'IDEA',
    'idea': 'IDEA',
    'vodafone': 'IDEA',
    'vi': 'IDEA',
    'idfc first bank': 'IDFCFIRSTB',
    'idfcfirstb': 'IDFCFIRSTB',
    'idfc': 'IDFCFIRSTB',
    'interglobe aviation': 'INDIGO',
    'indigo': 'INDIGO',
    'interglobe': 'INDIGO',
    'indusind bank': 'INDUSINDBK',
    'indusindbk': 'INDUSINDBK',
    'indusind': 'INDUSINDBK',
    'indus towers': 'INDUSTOWER',
    'industower': 'INDUSTOWER',
    'indus': 'INDUSTOWER',
    'infosys': 'INFY',
    'infy': 'INFY',
    'infosys limited': 'INFY',
    'inox leisure': 'INOXLEISUR',
    'inoxleisur': 'INOXLEISUR',
    'inox': 'INOXLEISUR',
    'indian oil corporation': 'IOC',
    'ioc': 'IOC',
    'indian oil': 'IOC',
    'irb infrastructure': 'IRB',
    'irb': 'IRB',
    'itc': 'ITC',
    'itc limited': 'ITC',
    'jindal steel and power': 'JINDALSTEL',
    'jindalstel': 'JINDALSTEL',
    'jspl': 'JINDALSTEL',
    'jk cement': 'JKCEMENT',
    'jkcement': 'JKCEMENT',
    'j kumar infraprojects': 'JKIL',
    'jkil': 'JKIL',
    'jsw steel': 'JSWSTEEL',
    'jswsteel': 'JSWSTEEL',
    'jsw': 'JSWSTEEL',
    'jubilant foodworks': 'JUBLFOOD',
    'jublfood': 'JUBLFOOD',
    'dominos': 'JUBLFOOD',
    'justdial': 'JUSTDIAL',
    'just dial': 'JUSTDIAL',
    'kec international': 'KEC',
    'kec': 'KEC',
    'kohinoor foods': 'KOHINOOR',
    'kohinoor': 'KOHINOOR',
    'kotak mahindra bank': 'KOTAKBANK',
    'kotak bank': 'KOTAKBANK',
    'kotak': 'KOTAKBANK',
    'krbl': 'KRBL',
    'krbl limited': 'KRBL',
    'india gate': 'KRBL',
    'dr lal path labs': 'LALPATHLAB',
    'lalpathlab': 'LALPATHLAB',
    'lal path lab': 'LALPATHLAB',
    'larsen and toubro': 'LT',
    'lt': 'LT',
    'l&t': 'LT',
    'larsen toubro': 'LT',
    'l&t finance holdings': 'LTFH',
    'ltfh': 'LTFH',
    'ltts': 'LTTS',
    'l&t technology services': 'LTTS',
    'larsen toubro tech': 'LTTS',
    'lupin': 'LUPIN',
    'lupin limited': 'LUPIN',
    'mahindra and mahindra': 'M&M',
    'm&m': 'M&M',
    'mahindra': 'M&M',
    'mahindra finance': 'MAHINDRAFIN',
    'mahindrafin': 'MAHINDRAFIN',
    'mahindra logistics': 'MAHLOG',
    'mahlog': 'MAHLOG',
    'manappuram finance': 'MANAPPURAM',
    'manappuram': 'MANAPPURAM',
    'marico': 'MARICO',
    'marico limited': 'MARICO',
    'maruti suzuki': 'MARUTI',
    'maruti': 'MARUTI',
    'maruti suzuki india': 'MARUTI',
    'matrimony': 'MATRIMONY',
    'matrimony.com': 'MATRIMONY',
    'max healthcare': 'MAXHEALTH',
    'maxhealth': 'MAXHEALTH',
    'max': 'MAXHEALTH',
    'united spirits': 'MCDOWELL-N',
    'mcdowell': 'MCDOWELL-N',
    'metropolis healthcare': 'METROPOLIS',
    'metropolis': 'METROPOLIS',
    'mindtree': 'MINDTREE',
    'mindtree limited': 'MINDTREE',
    'mobikwik': 'MOBIKWIK',
    'mobikwik systems': 'MOBIKWIK',
    'moil': 'MOIL',
    'manganese ore india': 'MOIL',
    'mphasis': 'MPHASIS',
    'mphasis limited': 'MPHASIS',
    'muthoot finance': 'MUTHOOTFIN',
    'muthootfin': 'MUTHOOTFIN',
    'muthoot': 'MUTHOOTFIN',
    'naukri': 'NAUKRI',
    'info edge': 'NAUKRI',
    'infoedge': 'NAUKRI',
    'ncc': 'NCC',
    'nagarjuna construction': 'NCC',
    'nestle india': 'NESTLEIND',
    'nestleind': 'NESTLEIND',
    'nestle': 'NESTLEIND',
    'narayana hrudayalaya': 'NH',
    'nh': 'NH',
    'narayana': 'NH',
    'nmdc': 'NMDC',
    'national mineral development': 'NMDC',
    'ntpc': 'NTPC',
    'national thermal power': 'NTPC',
    'national thermal power corporation': 'NTPC',
    'nykaa': 'NYKAA',
    'fsnl': 'NYKAA',
    'nykaa limited': 'NYKAA',
    'fashion and lifestyle': 'NYKAA',
    'ongc': 'ONGC',
    'oil and natural gas corporation': 'ONGC',
    'page industries': 'PAGEIND',
    'pageind': 'PAGEIND',
    'jockey': 'PAGEIND',
    'parag milk foods': 'PARAGMILK',
    'paragmilk': 'PARAGMILK',
    'go cheese': 'PARAGMILK',
    'paytm': 'PAYTM',
    'one97 communications': 'PAYTM',
    'one97': 'PAYTM',
    'persistent systems': 'PERSISTENT',
    'persistent': 'PERSISTENT',
    'pnb': 'PNB',
    'punjab national bank': 'PNB',
    'policybazaar': 'POLICYBZR',
    'pb fintech': 'POLICYBZR',
    'policy bazaar': 'POLICYBZR',
    'power grid corporation': 'POWERGRID',
    'powergrid': 'POWERGRID',
    'power grid': 'POWERGRID',
    'pvr': 'PVR',
    'pvr limited': 'PVR',
    'ramco cements': 'RAMCOCEM',
    'ramcocem': 'RAMCOCEM',
    'ramco': 'RAMCOCEM',
    'ratnamani metals': 'RATNAMANI',
    'ratnamani': 'RATNAMANI',
    'raymond': 'RAYMOND',
    'raymond limited': 'RAYMOND',
    'rbl bank': 'RBLBANK',
    'rblbank': 'RBLBANK',
    'relaxo footwears': 'RELAXO',
    'relaxo': 'RELAXO',
    'reliance industries': 'RELIANCE',
    'reliance': 'RELIANCE',
    'ril': 'RELIANCE',
    'reliance jio': 'RELIANCE',
    'jio': 'RELIANCE',
    'steel authority of india': 'SAIL',
    'sail': 'SAIL',
    'sbi life': 'SBILIFE',
    'sbilife': 'SBILIFE',
    'state bank of india': 'SBIN',
    'sbi': 'SBIN',
    'state bank': 'SBIN',
    'shoppers stop': 'SHOPERSTOP',
    'shoperstop': 'SHOPERSTOP',
    'shree cement': 'SHREECEM',
    'shreecem': 'SHREECEM',
    'spicejet': 'SPICEJET',
    'spicejet limited': 'SPICEJET',
    'diagnostic robotic': 'SRL',
    'srl': 'SRL',
    'shriram transport': 'SRTRANSFIN',
    'srtransfin': 'SRTRANSFIN',
    'shriram': 'SRTRANSFIN',
    'star india': 'STAR',
    'star': 'STAR',
    'sun pharmaceutical': 'SUNPHARMA',
    'sunpharma': 'SUNPHARMA',
    'sun pharma': 'SUNPHARMA',
    'swiggy': 'SWIGGY',
    'swiggy limited': 'SWIGGY',
    'tata communications': 'TATACOMM',
    'tatacomm': 'TATACOMM',
    'tata consumer products': 'TATACONSUM',
    'tataconsum': 'TATACONSUM',
    'tata tea': 'TATACONSUM',
    'tata motors': 'TATAMOTORS',
    'tatamotors': 'TATAMOTORS',
    'tata motor': 'TATAMOTORS',
    'tata power': 'TATAPOWER',
    'tatapower': 'TATAPOWER',
    'tata steel': 'TATASTEEL',
    'tatasteel': 'TATASTEEL',
    'transport corporation': 'TCIEXP',
    'tciexp': 'TCIEXP',
    'tci': 'TCIEXP',
    'tata consultancy services': 'TCS',
    'tcs': 'TCS',
    'tata consultancy': 'TCS',
    'tech mahindra': 'TECHM',
    'techm': 'TECHM',
    'tech m': 'TECHM',
    'thyrocare technologies': 'THYROCARE',
    'thyrocare': 'THYROCARE',
    'tips industries': 'TIPS',
    'tips': 'TIPS',
    'trent': 'TRENT',
    'trent limited': 'TRENT',
    'westside': 'TRENT',
    'trident': 'TRIDENT',
    'trident limited': 'TRIDENT',
    'tvs motor': 'TVSMOTOR',
    'tvsmotor': 'TVSMOTOR',
    'tvs': 'TVSMOTOR',
    'united breweries': 'UBL',
    'ubl': 'UBL',
    'kingfisher': 'UBL',
    'ujjivan small finance bank': 'UJJIVANSFB',
    'ujjivansfb': 'UJJIVANSFB',
    'ujjivan': 'UJJIVANSFB',
    'ultratech cement': 'ULTRACEMCO',
    'ultracemco': 'ULTRACEMCO',
    'ultratech': 'ULTRACEMCO',
    'unacademy': 'UNACADEMY',
    'unacademy group': 'UNACADEMY',
    'union bank': 'UNIONBANK',
    'unionbank': 'UNIONBANK',
    'varun beverages': 'VBL',
    'vbl': 'VBL',
    'pepsi': 'VBL',
    'vedanta': 'VEDL',
    'vedl': 'VEDL',
    'vedanta limited': 'VEDL',
    'v mart retail': 'VMART',
    'vmart': 'VMART',
    'voltas': 'VOLTAS',
    'voltas limited': 'VOLTAS',
    'welspun india': 'WELSPUNIND',
    'welspunind': 'WELSPUNIND',
    'welspun': 'WELSPUNIND',
    'westlife development': 'WESTLIFE',
    'westlife': 'WESTLIFE',
    'mcdonalds': 'WESTLIFE',
    'whirlpool of india': 'WHIRLPOOL',
    'whirlpool': 'WHIRLPOOL',
    'wipro': 'WIPRO',
    'wipro limited': 'WIPRO',
    'yes bank': 'YESBANK',
    'yesbank': 'YESBANK',
    'zee entertainment': 'ZEEL',
    'zeel': 'ZEEL',
    'zee': 'ZEEL',
    'zomato': 'ZOMATO',
    'zomato limited': 'ZOMATO'
  };
