version: '3.8'

services:
  stock-scraper:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_GOOGLE_SEARCH_API_KEY=${REACT_APP_GOOGLE_SEARCH_API_KEY}
      - REACT_APP_GOOGLE_SEARCH_ENGINE_ID=${REACT_APP_GOOGLE_SEARCH_ENGINE_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s